### ISSUE TITLE
crawl: error: running 'scrapy crawl' with more than one spider is no longer supported

### ISSUE THREAD

**Issue by amirktc** [cpatrickalves/scraping-etsy#1]
crawl: error: running 'scrapy crawl' with more than one spider is no longer supported

**Comment by cpatrickalves** [comment]
Hi @amirktc 
I didn't understand your issue. 

Are you trying to run with more than one spider?

**Comment by cpatrickalves** [comment]
As I've got no response for this issue I'll close it.
